export interface RazorpayCheckoutOptions {
  key?: string;
  amount: number; // in paise or rupees
  currency: string;
  name: string;
  description: string;
  order_id: string;
  prefill?: {
    name?: string;
    email?: string;
    contact?: string;
  };
  notes?: Record<string, string>;
  theme?: {
    color?: string;
  };
  handler?: (response: {
    razorpay_payment_id: string;
    razorpay_order_id: string;
    razorpay_signature: string;
  }) => void;
  modal?: {
    ondismiss?: () => void;
  };
}

export class RazorpayService {
  private static isTestMode: boolean = true;

  public static getMode(): 'test' | 'production' {
    return this.isTestMode ? 'test' : 'production';
  }

  // Create simulated order
  public static async createTestOrder(amountInRupees: number, bookingRef: string) {
    const orderId = `order_test_${Date.now()}_${Math.floor(Math.random() * 1000)}`;
    return {
      id: orderId,
      amount: amountInRupees * 100, // paise
      currency: 'INR',
      receipt: bookingRef,
      status: 'created',
      mode: 'test',
    };
  }

  // Verify Razorpay signature (simulated server-side HMAC-SHA256 check)
  public static verifySignature(
    orderId: string,
    paymentId: string,
    signature: string
  ): boolean {
    if (!orderId || !paymentId) return false;
    // In test mode, signatures generated by our test checkout start with 'test_sig_'
    return signature.startsWith('test_sig_') || signature.length > 20;
  }
}
