import React from 'react';
import { PageId } from '../types';
import { Users2, HeartHandshake, ShieldCheck, TreePine, Droplet, Hammer, ArrowRight } from 'lucide-react';

interface CommunityViewProps {
  onNavigate: (page: PageId) => void;
}

export const CommunityView: React.FC<CommunityViewProps> = ({ onNavigate }) => {
  return (
    <div className="py-12 sm:py-20 space-y-16">
      {/* Header Banner */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 space-y-4">
        <span className="text-xs uppercase tracking-widest text-[#B85D28] font-semibold">
          The Purpose Beyond Enterprise
        </span>
        <h1 className="text-4xl sm:text-6xl font-serif font-bold text-[#1C1917] tracking-tight leading-tight">
          Community Development
        </h1>
        <p className="text-lg sm:text-xl font-serif italic text-[#645E59]">
          The enterprise-supported model: building local capability, dignity, and autonomy without fostering dependency.
        </p>
        <div className="h-0.5 w-24 bg-[#B85D28] pt-0.5 mt-4" />
      </div>

      {/* Narrative: The Community as the Hero */}
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 space-y-8 text-[#38332E] leading-relaxed text-base sm:text-lg">
        <div className="space-y-4">
          <span className="text-xs uppercase tracking-widest text-[#8C827A] font-mono">
            CORE PHILOSOPHY
          </span>
          <h2 className="text-2xl sm:text-3xl font-serif font-bold text-[#163E2E]">
            The Community is the Protagonist
          </h2>
          <p>
            In conventional development campaigns, rural villagers are frequently portrayed as helpless victims awaiting external rescue. In Uttarkunth, we reject that paternalistic framing entirely.
          </p>
          <p>
            Himalayan mountain villagers possess centuries of accumulated ecological knowledge, architectural mastery, agricultural resilience, and communal solidarity. The community is the true hero of this story.
          </p>
          <p>
            Our role as an entrepreneurial ecosystem is not to "save" the village, but to build operational vehicles and commercial infrastructure that allow local capabilities to earn dignified returns and command respect in the wider world.
          </p>
        </div>

        {/* The 10% Guiding Principle */}
        <div className="bg-[#F5EFEB] border border-[#E8E2D9] p-6 sm:p-8 space-y-4">
          <div className="flex items-center gap-2">
            <span className="text-xs uppercase tracking-widest font-bold text-[#163E2E]">
              Guiding Principle
            </span>
            <span className="text-xs text-[#645E59]">· Internal Benchmark</span>
          </div>
          <h3 className="text-xl sm:text-2xl font-serif font-bold text-[#163E2E]">
            The ~10% Community Allocation Concept
          </h3>
          <p className="text-sm text-[#4A453F] leading-relaxed">
            As discussed in the foundational Uttarkunth framework, our vision includes a voluntary guiding concept: designating approximately <strong>10% of operational surplus</strong> generated by our commercial ventures directly toward practical community initiatives.
          </p>
          <div className="bg-white border-l-2 border-[#163E2E] p-4 text-xs text-[#5A544E] leading-relaxed space-y-2">
            <p>
              <strong>Important Transparency Note:</strong> This allocation is an internal operating benchmark subject entirely to real-world financial health, working capital reserves, and commercial viability. It is <em>not</em> a legally binding commitment or a public donation subscription.
            </p>
            <p>
              First, businesses must stand securely on their own feet, meet payroll, and sustain operations; only then can surplus be channeled sustainably into community initiatives without jeopardizing enterprise longevity.
            </p>
          </div>
        </div>
      </div>

      {/* Practical Living Laboratory Focus Areas */}
      <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 space-y-10">
        <div className="text-center space-y-3 max-w-2xl mx-auto">
          <span className="text-xs uppercase tracking-widest text-[#163E2E] font-semibold">
            Action on the Slopes
          </span>
          <h2 className="text-3xl sm:text-4xl font-serif font-bold text-[#1C1917]">
            Active Community Workstreams
          </h2>
          <p className="text-sm text-[#645E59]">
            Where Uttarkunth team energy, tools, and resources are deployed in the village.
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {/* Card 1 */}
          <div className="bg-white border border-[#E8E2D9] p-6 space-y-3">
            <div className="w-10 h-10 bg-[#F3F7F5] text-[#163E2E] flex items-center justify-center">
              <TreePine size={20} />
            </div>
            <h3 className="text-xl font-serif font-bold text-[#163E2E]">
              Slope Care & Native Afforestation
            </h3>
            <p className="text-xs sm:text-sm text-[#4A453F] leading-relaxed">
              Working with village youth to identify landslide-prone slopes and plant deep-rooting native oak (Banj) and rhododendron saplings that retain water and stabilize the soil.
            </p>
          </div>

          {/* Card 2 */}
          <div className="bg-white border border-[#E8E2D9] p-6 space-y-3">
            <div className="w-10 h-10 bg-[#F3F7F5] text-[#163E2E] flex items-center justify-center">
              <Droplet size={20} />
            </div>
            <h3 className="text-xl font-serif font-bold text-[#163E2E]">
              Spring-Water (Naula) Stewardship
            </h3>
            <p className="text-xs sm:text-sm text-[#4A453F] leading-relaxed">
              Clearing debris from traditional subterranean mountain springs, preventing contamination from runoff, and documenting water quality alongside village elders.
            </p>
          </div>

          {/* Card 3 */}
          <div className="bg-white border border-[#E8E2D9] p-6 space-y-3">
            <div className="w-10 h-10 bg-[#F3F7F5] text-[#163E2E] flex items-center justify-center">
              <Hammer size={20} />
            </div>
            <h3 className="text-xl font-serif font-bold text-[#163E2E]">
              Vernacular Masonry Apprenticeships
            </h3>
            <p className="text-xs sm:text-sm text-[#4A453F] leading-relaxed">
              Connecting senior stone-cutters and wood-carvers with young villagers to construct earthquake-resistant structures that celebrate indigenous Himalayan aesthetics.
            </p>
          </div>

          {/* Card 4 */}
          <div className="bg-white border border-[#E8E2D9] p-6 space-y-3">
            <div className="w-10 h-10 bg-[#F3F7F5] text-[#163E2E] flex items-center justify-center">
              <Users2 size={20} />
            </div>
            <h3 className="text-xl font-serif font-bold text-[#163E2E]">
              Youth Hospitality & Digital Skills
            </h3>
            <p className="text-xs sm:text-sm text-[#4A453F] leading-relaxed">
              Practical on-the-job training in front-desk management, hygienic food preparation, storytelling, photography, and digital marketing at Yash Home Stay and Uttarkunth Café.
            </p>
          </div>

          {/* Card 5 */}
          <div className="bg-white border border-[#E8E2D9] p-6 space-y-3">
            <div className="w-10 h-10 bg-[#F3F7F5] text-[#163E2E] flex items-center justify-center">
              <ShieldCheck size={20} />
            </div>
            <h3 className="text-xl font-serif font-bold text-[#163E2E]">
              Clean Trails & Plastic Segregation
            </h3>
            <p className="text-xs sm:text-sm text-[#4A453F] leading-relaxed">
              Organizing periodic community trail-sweeps along pilgrim paths and testing small-scale compaction and collection solutions to prevent plastic incineration in villages.
            </p>
          </div>

          {/* Card 6 */}
          <div className="bg-white border border-[#E8E2D9] p-6 space-y-3">
            <div className="w-10 h-10 bg-[#F3F7F5] text-[#163E2E] flex items-center justify-center">
              <HeartHandshake size={20} />
            </div>
            <h3 className="text-xl font-serif font-bold text-[#163E2E]">
              Village Council (Panchayat) Dialogue
            </h3>
            <p className="text-xs sm:text-sm text-[#4A453F] leading-relaxed">
              Ensuring all new activities receive the blessing and input of village elders and local governing bodies, preventing conflict and respecting local community traditions.
            </p>
          </div>
        </div>
      </div>

      {/* Navigation Call to Action */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 pt-8 flex flex-col sm:flex-row items-center justify-between gap-4 border-t border-[#E8E2D9]">
        <button
          onClick={() => onNavigate('media')}
          className="text-xs font-semibold uppercase tracking-widest text-[#163E2E] hover:underline"
        >
          Next: Watch Our Stories & Media Documentaries →
        </button>
        <button
          onClick={() => onNavigate('join')}
          className="px-6 py-3 text-xs font-semibold uppercase tracking-widest bg-[#B85D28] text-white hover:bg-[#964218] transition-colors shadow-sm"
        >
          Participate in Community Initiatives
        </button>
      </div>
    </div>
  );
};
